"use client";

import Sidebar from "@/components/Sidebar";
import GlassCard from "@/components/ui/GlassCard";
import GlowButton from "@/components/ui/GlowButton";
import { 
  FileText, 
  Download, 
  Search, 
  Filter, 
  Calendar,
  Share2,
  FileCheck,
  Zap,
  TrendingUp,
  ChevronRight
} from "lucide-react";
import { motion } from "framer-motion";

const reports = [
  { 
    id: 1, 
    title: "Q2 Strategic Intelligence Audit", 
    date: "May 12, 2026", 
    type: "PDF Audit", 
    status: "Verified",
    summary: "Deep-dive analysis of market shifts and internal growth velocity metrics."
  },
  { 
    id: 2, 
    title: "Customer Psychology Deep Dive", 
    date: "May 08, 2026", 
    type: "JSON Analysis", 
    status: "New",
    summary: "Synthesis of emotional sentiment data from 5,000+ support interactions."
  },
  { 
    id: 3, 
    title: "Competitor Displacement Strategy", 
    date: "May 01, 2026", 
    type: "Strategic Deck", 
    status: "Verified",
    summary: "A 45-page blueprint for displacing incumbent players in the mid-market segment."
  },
  { 
    id: 4, 
    title: "Burn Rate & Runway Projection", 
    date: "Apr 28, 2026", 
    type: "Financial Model", 
    status: "Verified",
    summary: "Automated simulation of runway under aggressive and conservative growth scenarios."
  },
];

export default function ReportsPage() {
  return (
    <div className="flex">
      <Sidebar />
      <main className="flex-1 ml-64 p-8">
        <div className="max-w-6xl mx-auto">
          <header className="mb-12 flex justify-between items-end">
            <div>
              <h1 className="text-3xl font-bold mb-2">Strategic Reports</h1>
              <p className="text-white/40 italic">High-fidelity intelligence assets generated by the neural engine.</p>
            </div>
            <div className="flex gap-4">
              <GlowButton variant="outline" className="flex items-center gap-2">
                <Filter className="w-4 h-4" /> Filter
              </GlowButton>
              <GlowButton className="flex items-center gap-2">
                <Zap className="w-4 h-4" /> Generate New Audit
              </GlowButton>
            </div>
          </header>

          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
            {/* Search & Categories */}
            <div className="space-y-6">
              <div className="glass px-4 py-3 rounded-xl flex items-center gap-3 border-white/5">
                <Search className="w-4 h-4 text-white/40" />
                <input 
                  type="text" 
                  placeholder="Search reports..." 
                  className="bg-transparent border-none outline-none text-sm text-white placeholder:text-white/20 w-full"
                />
              </div>

              <div className="space-y-2">
                <p className="text-[10px] uppercase font-bold text-white/30 px-2 mb-4">Categories</p>
                {[
                  { name: "Strategic Audits", count: 12 },
                  { name: "Market Intelligence", count: 8 },
                  { name: "Financial Simulations", count: 15 },
                  { name: "Founder Psychology", count: 4 },
                ].map((cat) => (
                  <div key={cat.name} className="flex justify-between items-center px-3 py-2 rounded-lg hover:bg-white/5 transition-colors cursor-pointer group">
                    <span className="text-sm text-white/60 group-hover:text-white transition-colors">{cat.name}</span>
                    <span className="text-xs bg-white/5 px-2 py-0.5 rounded text-white/40">{cat.count}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Reports List */}
            <div className="lg:col-span-3 space-y-4">
              {reports.map((report, i) => (
                <motion.div
                  key={report.id}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1 }}
                >
                  <GlassCard className="p-0 overflow-hidden hover:border-pivot-blue/30 transition-all border-white/5">
                    <div className="p-6 flex items-start gap-6">
                      <div className="w-14 h-14 rounded-xl bg-pivot-blue/10 flex items-center justify-center shrink-0">
                        <FileText className="text-pivot-blue w-7 h-7" />
                      </div>
                      <div className="flex-1">
                        <div className="flex justify-between items-start mb-2">
                          <div>
                            <h3 className="font-bold text-lg">{report.title}</h3>
                            <div className="flex items-center gap-4 mt-1">
                              <span className="flex items-center gap-1.5 text-xs text-white/40">
                                <Calendar className="w-3 h-3" /> {report.date}
                              </span>
                              <span className="flex items-center gap-1.5 text-xs text-white/40">
                                <FileCheck className="w-3 h-3 text-green-400" /> {report.status}
                              </span>
                            </div>
                          </div>
                          <div className="flex gap-2">
                            <button className="p-2 glass rounded-lg hover:bg-white/10 transition-colors">
                              <Share2 className="w-4 h-4 text-white/60" />
                            </button>
                            <button className="p-2 glass rounded-lg hover:bg-white/10 transition-colors">
                              <Download className="w-4 h-4 text-white/60" />
                            </button>
                          </div>
                        </div>
                        <p className="text-sm text-white/60 leading-relaxed max-w-2xl mb-4">
                          {report.summary}
                        </p>
                        <div className="flex items-center gap-4">
                          <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-white/5 text-white/40 border border-white/5">
                            {report.type}
                          </span>
                          <button className="text-xs font-bold text-pivot-blue flex items-center gap-1 hover:gap-2 transition-all">
                            Open Intelligence Asset <ChevronRight className="w-3 h-3" />
                          </button>
                        </div>
                      </div>
                    </div>
                  </GlassCard>
                </motion.div>
              ))}

              <div className="pt-8 text-center">
                <p className="text-white/20 text-xs italic mb-4">All reports are encrypted with post-quantum security protocols.</p>
                <GlowButton variant="outline" className="text-xs py-2">
                  View Archive
                </GlowButton>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
